/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201801251438.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_LUXOFT_CHARACTERSERVICE_Character_Service_DBUS_STUB_ADAPTER_HPP_
#define V1_COM_LUXOFT_CHARACTERSERVICE_Character_Service_DBUS_STUB_ADAPTER_HPP_

#include <v1/com/luxoft/characterservice/CharacterServiceStub.hpp>
#include "v1/com/luxoft/characterservice/CharacterServiceDBusDeployment.hpp"
#include <v1/com/luxoft/characterservice/CharacterServiceDBusDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusAddressTranslator.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusDeployment.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace com {
namespace luxoft {
namespace characterservice {

template <typename _Stub = ::v1::com::luxoft::characterservice::CharacterServiceStub, typename... _Stubs>
class CharacterServiceDBusStubAdapterInternal
    : public virtual CharacterServiceStubAdapter,
      public CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...>
     {
public:
    typedef CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...> CharacterServiceDBusStubAdapterHelper;

    ~CharacterServiceDBusStubAdapterInternal() {
        deactivateManagedInstances();
        CharacterServiceDBusStubAdapterHelper::deinit();
    }

    virtual bool hasFreedesktopProperties() {
        return false;
    }

    inline static const char* getInterface() {
        return CharacterService::getInterface();
    }

    void deactivateManagedInstances() {
    }

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::com::luxoft::characterservice::CharacterServiceStub,
        CommonAPI::Version
        > getCharacterServiceInterfaceVersionStubDispatcher;

    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::com::luxoft::characterservice::CharacterServiceStub,
        std::tuple< CharacterService::Arm>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::DBus::StringDeployment>
    
        > armUpStubDispatcher;

    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::com::luxoft::characterservice::CharacterServiceStub,
        std::tuple< CharacterService::Arm>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::DBus::StringDeployment>
    
        > armDownStubDispatcher;

    CharacterServiceDBusStubAdapterInternal(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
    : CommonAPI::DBus::DBusStubAdapter(_address, _connection,false),
      CharacterServiceDBusStubAdapterHelper(_address, _connection, false, _stub) {
        CharacterServiceDBusStubAdapterHelper::addStubDispatcher({ "ArmUp", "i" }, &armUpStubDispatcher);
        CharacterServiceDBusStubAdapterHelper::addStubDispatcher({ "ArmDown", "i" }, &armDownStubDispatcher);
        CharacterServiceDBusStubAdapterHelper::addStubDispatcher({ "getInterfaceVersion", "" }, &getCharacterServiceInterfaceVersionStubDispatcher);
    }

protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const {
        static const std::string introspectionData =
            "<method name=\"getInterfaceVersion\">\n"
                "<arg name=\"value\" type=\"uu\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"ArmUp\">\n"
            "<arg name=\"_arm\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"s\" direction=\"out\" />\n"
            "</method>\n"
            "<method name=\"ArmDown\">\n"
            "<arg name=\"_arm\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"s\" direction=\"out\" />\n"
            "</method>\n"
            ;
        return introspectionData.c_str();
    }

private:
};


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
    ::v1::com::luxoft::characterservice::CharacterServiceStub,
    CommonAPI::Version
    > CharacterServiceDBusStubAdapterInternal<_Stub, _Stubs...>::getCharacterServiceInterfaceVersionStubDispatcher(&CharacterServiceStub::lockInterfaceVersionAttribute, &CharacterServiceStub::getInterfaceVersion, "uu");


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::com::luxoft::characterservice::CharacterServiceStub,
    std::tuple< CharacterService::Arm>,
    std::tuple< std::string>,
    std::tuple< CommonAPI::EmptyDeployment>,
    std::tuple< CommonAPI::DBus::StringDeployment>

    > CharacterServiceDBusStubAdapterInternal<_Stub, _Stubs...>::armUpStubDispatcher(
    &CharacterServiceStub::ArmUp, "s",
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::DBus::StringDeployment* >(nullptr)));


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::com::luxoft::characterservice::CharacterServiceStub,
    std::tuple< CharacterService::Arm>,
    std::tuple< std::string>,
    std::tuple< CommonAPI::EmptyDeployment>,
    std::tuple< CommonAPI::DBus::StringDeployment>

    > CharacterServiceDBusStubAdapterInternal<_Stub, _Stubs...>::armDownStubDispatcher(
    &CharacterServiceStub::ArmDown, "s",
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::DBus::StringDeployment* >(nullptr)));


template <typename _Stub = ::v1::com::luxoft::characterservice::CharacterServiceStub, typename... _Stubs>
class CharacterServiceDBusStubAdapter
    : public CharacterServiceDBusStubAdapterInternal<_Stub, _Stubs...>,
      public std::enable_shared_from_this< CharacterServiceDBusStubAdapter<_Stub, _Stubs...>> {
public:
    CharacterServiceDBusStubAdapter(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
        : CommonAPI::DBus::DBusStubAdapter(
            _address,
            _connection,
            false),
          CharacterServiceDBusStubAdapterInternal<_Stub, _Stubs...>(
            _address,
            _connection,
            _stub) {
    }
};

} // namespace characterservice
} // namespace luxoft
} // namespace com
} // namespace v1

#endif // V1_COM_LUXOFT_CHARACTERSERVICE_Character_Service_DBUS_STUB_ADAPTER_HPP_
