/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201801251447.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/com/luxoft/characterservice/CharacterServiceStubDefault.hpp>
#include <assert.h>

namespace v1 {
namespace com {
namespace luxoft {
namespace characterservice {

CharacterServiceStubDefault::CharacterServiceStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(CharacterService::getInterfaceVersion()) {
}

const CommonAPI::Version& CharacterServiceStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

CharacterServiceStubRemoteEvent* CharacterServiceStubDefault::initStubAdapter(const std::shared_ptr< CharacterServiceStubAdapter> &_adapter) {
    CommonAPI::Stub<CharacterServiceStubAdapter, CharacterServiceStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}


void CharacterServiceStubDefault::ArmUp(const std::shared_ptr<CommonAPI::ClientId> _client, CharacterService::Arm _arm, ArmUpReply_t _reply) {
    (void)_client;
    (void)_arm;
    std::string result = "";
    _reply(result);
}

void CharacterServiceStubDefault::ArmDown(const std::shared_ptr<CommonAPI::ClientId> _client, CharacterService::Arm _arm, ArmDownReply_t _reply) {
    (void)_client;
    (void)_arm;
    std::string result = "";
    _reply(result);
}




CharacterServiceStubDefault::RemoteEventHandler::RemoteEventHandler(CharacterServiceStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace characterservice
} // namespace luxoft
} // namespace com
} // namespace v1
