/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201801251447.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/com/luxoft/humancharacterservice/HumanCharacterServiceStubDefault.hpp>
#include <assert.h>

namespace v1 {
namespace com {
namespace luxoft {
namespace humancharacterservice {

HumanCharacterServiceStubDefault::HumanCharacterServiceStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(HumanCharacterService::getInterfaceVersion()) {
}

const CommonAPI::Version& HumanCharacterServiceStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

HumanCharacterServiceStubRemoteEvent* HumanCharacterServiceStubDefault::initStubAdapter(const std::shared_ptr< HumanCharacterServiceStubAdapter> &_adapter) {
    CommonAPI::Stub<HumanCharacterServiceStubAdapter, HumanCharacterServiceStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}


void HumanCharacterServiceStubDefault::ArmsUp(const std::shared_ptr<CommonAPI::ClientId> _client, ArmsUpReply_t _reply) {
    (void)_client;
    std::string result = "";
    _reply(result);
}

void HumanCharacterServiceStubDefault::ArmsDown(const std::shared_ptr<CommonAPI::ClientId> _client, ArmsDownReply_t _reply) {
    (void)_client;
    std::string result = "";
    _reply(result);
}




HumanCharacterServiceStubDefault::RemoteEventHandler::RemoteEventHandler(HumanCharacterServiceStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace humancharacterservice
} // namespace luxoft
} // namespace com
} // namespace v1
